import type { QuizQuestion } from "./types"

type QuizId = "q-cond-prob" | "q-garch" | "q-execution" | "q-risk-measures"

const QUESTIONS_PER_POOL = 20
export const QUESTIONS_PER_ATTEMPT = 5

function createMcq(question: Omit<QuizQuestion, "type">): QuizQuestion {
  return {
    ...question,
    type: "multiple-choice",
  }
}

function shuffle<T>(items: T[]): T[] {
  const copy = [...items]
  for (let i = copy.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    const temp = copy[i]
    copy[i] = copy[j]
    copy[j] = temp
  }
  return copy
}

const conditionalProbabilityQuestions: QuizQuestion[] = [
  createMcq({
    id: "q1-01",
    text: "If P(A)=0.4, P(B|A)=0.5, and P(B|A')=0.2, what is P(A|B)?",
    options: ["0.625", "0.500", "0.320", "0.800"],
    correctAnswer: "0.625",
    explanation: "Bayes: P(A|B)=0.5*0.4 / (0.5*0.4 + 0.2*0.6)=0.2/0.32=0.625.",
    topicTags: ["probability"],
    difficulty: "Intermediate",
  }),
  createMcq({
    id: "q1-02",
    text: "For independent events A and B with P(A)=0.5, what is P(A|B)?",
    options: ["0.5", "0.0", "1.0", "Cannot be determined"],
    correctAnswer: "0.5",
    explanation: "Independence implies P(A|B)=P(A).",
    topicTags: ["probability"],
    difficulty: "Beginner",
  }),
  createMcq({
    id: "q1-03",
    text: "Given P(A∩B)=0.18 and P(B)=0.6, what is P(A|B)?",
    options: ["0.30", "0.60", "0.18", "0.42"],
    correctAnswer: "0.30",
    explanation: "P(A|B)=P(A∩B)/P(B)=0.18/0.6=0.30.",
    topicTags: ["probability"],
    difficulty: "Beginner",
  }),
  createMcq({
    id: "q1-04",
    text: "In a regime model, P(trending)=0.7, P(signal|trending)=0.9, P(signal|mean-reverting)=0.2. What is P(signal)?",
    options: ["0.69", "0.63", "0.83", "0.20"],
    correctAnswer: "0.69",
    explanation: "Law of total probability: 0.9*0.7 + 0.2*0.3 = 0.69.",
    topicTags: ["probability", "time-series"],
    difficulty: "Intermediate",
  }),
  createMcq({
    id: "q1-05",
    text: "A disease prevalence is 1%. Test sensitivity is 95%, specificity is 90%. Approximate P(disease|positive).",
    options: ["8.8%", "50.0%", "90.0%", "95.0%"],
    correctAnswer: "8.8%",
    explanation: "Bayes: 0.0095 / (0.0095 + 0.099) ≈ 0.0876.",
    topicTags: ["probability", "statistics"],
    difficulty: "Advanced",
  }),
  createMcq({
    id: "q1-06",
    text: "If A and B are mutually exclusive with P(B)>0, what is P(A|B)?",
    options: ["0", "P(A)", "P(B)", "1"],
    correctAnswer: "0",
    explanation: "Mutually exclusive events cannot occur together, so P(A∩B)=0.",
    topicTags: ["probability"],
    difficulty: "Beginner",
  }),
  createMcq({
    id: "q1-07",
    text: "If A is a subset of B and P(B)>0, which expression equals P(A|B)?",
    options: ["P(A)/P(B)", "P(B)/P(A)", "P(A)P(B)", "P(A)+P(B)"],
    correctAnswer: "P(A)/P(B)",
    explanation: "When A⊆B, A∩B=A, so P(A|B)=P(A)/P(B).",
    topicTags: ["probability"],
    difficulty: "Intermediate",
  }),
  createMcq({
    id: "q1-08",
    text: "If P(A|B)=0.4 and P(B)=0.5, what is P(A∩B)?",
    options: ["0.20", "0.40", "0.80", "0.10"],
    correctAnswer: "0.20",
    explanation: "P(A∩B)=P(A|B)P(B)=0.4*0.5=0.20.",
    topicTags: ["probability"],
    difficulty: "Beginner",
  }),
  createMcq({
    id: "q1-09",
    text: "Two fair dice are rolled. What is P(sum=8 | at least one die is 4)?",
    options: ["1/11", "1/6", "5/36", "1/9"],
    correctAnswer: "1/11",
    explanation: "Conditioned sample space has 11 outcomes; only (4,4) sums to 8.",
    topicTags: ["probability"],
    difficulty: "Advanced",
  }),
  createMcq({
    id: "q1-10",
    text: "If P(A|B) > P(A), what does this suggest about A and B?",
    options: ["Positive association", "Independence", "Mutual exclusivity", "A implies not B"],
    correctAnswer: "Positive association",
    explanation: "Conditioning on B raises the probability of A.",
    topicTags: ["probability", "statistics"],
    difficulty: "Intermediate",
  }),
  createMcq({
    id: "q1-11",
    text: "With prior P(bull)=0.6, P(signal|bull)=0.7, and P(signal|bear)=0.4, what is P(bull|signal)?",
    options: ["0.724", "0.600", "0.875", "0.420"],
    correctAnswer: "0.724",
    explanation: "Bayes: 0.42/(0.42+0.16)=0.724.",
    topicTags: ["probability", "time-series"],
    difficulty: "Intermediate",
  }),
  createMcq({
    id: "q1-12",
    text: "Which identity is the chain rule for three events?",
    options: [
      "P(A∩B∩C)=P(A)P(B|A)P(C|A,B)",
      "P(A∩B∩C)=P(A)+P(B)+P(C)",
      "P(A∩B∩C)=P(A|B|C)",
      "P(A∩B∩C)=P(A)P(B)P(C)",
    ],
    correctAnswer: "P(A∩B∩C)=P(A)P(B|A)P(C|A,B)",
    explanation: "Successive conditioning expands joint probabilities.",
    topicTags: ["probability"],
    difficulty: "Intermediate",
  }),
  createMcq({
    id: "q1-13",
    text: "If P(A∩B)=P(A)P(B), what can be concluded?",
    options: ["A and B are independent", "A and B are mutually exclusive", "A implies B", "No relation"],
    correctAnswer: "A and B are independent",
    explanation: "This is the defining property of independence.",
    topicTags: ["probability"],
    difficulty: "Beginner",
  }),
  createMcq({
    id: "q1-14",
    text: "If P(A|B)=1, which statement is correct?",
    options: ["B is a subset of A", "A and B are independent", "A is a subset of B", "P(B|A)=1 always"],
    correctAnswer: "B is a subset of A",
    explanation: "Whenever B occurs, A occurs as well.",
    topicTags: ["probability"],
    difficulty: "Intermediate",
  }),
  createMcq({
    id: "q1-15",
    text: "Given a red card is drawn from a standard deck, what is P(heart | red)?",
    options: ["1/2", "1/4", "13/52", "2/3"],
    correctAnswer: "1/2",
    explanation: "Among 26 red cards, 13 are hearts.",
    topicTags: ["probability"],
    difficulty: "Beginner",
  }),
  createMcq({
    id: "q1-16",
    text: "Urn 1 is chosen with probability 0.3 and has 70% red balls. Urn 2 is chosen with probability 0.7 and has 20% red balls. Given a red draw, what is P(Urn 1)?",
    options: ["0.60", "0.30", "0.45", "0.21"],
    correctAnswer: "0.60",
    explanation: "Bayes: 0.3*0.7 / (0.3*0.7 + 0.7*0.2)=0.21/0.35=0.60.",
    topicTags: ["probability"],
    difficulty: "Advanced",
  }),
  createMcq({
    id: "q1-17",
    text: "Which statement describes the law of total probability?",
    options: [
      "P(A)=Σ P(A|B_i)P(B_i) over a partition {B_i}",
      "P(A|B)=P(B|A)",
      "P(A∩B)=P(A)+P(B)",
      "P(A)=1-P(A|B)",
    ],
    correctAnswer: "P(A)=Σ P(A|B_i)P(B_i) over a partition {B_i}",
    explanation: "It decomposes P(A) across mutually exclusive/exhaustive cases.",
    topicTags: ["probability"],
    difficulty: "Intermediate",
  }),
  createMcq({
    id: "q1-18",
    text: "Which is the tower property of expectation?",
    options: ["E[E[X|Y]] = E[X]", "E[X|Y] = E[Y|X]", "E[X+Y] = E[X]E[Y]", "E[X|Y]=E[X]/E[Y]"],
    correctAnswer: "E[E[X|Y]] = E[X]",
    explanation: "Conditioning then averaging returns the unconditional mean.",
    topicTags: ["probability"],
    difficulty: "Intermediate",
  }),
  createMcq({
    id: "q1-19",
    text: "If P(A)=0.2 and P(B)=0.4 with independent A,B, what is P(A∩B)?",
    options: ["0.08", "0.60", "0.20", "0.40"],
    correctAnswer: "0.08",
    explanation: "For independent events: P(A∩B)=P(A)P(B).",
    topicTags: ["probability"],
    difficulty: "Beginner",
  }),
  createMcq({
    id: "q1-20",
    text: "Which expression for Bayes' theorem is correct (for P(B)>0)?",
    options: [
      "P(A|B)=P(B|A)P(A)/P(B)",
      "P(A|B)=P(A)/P(B|A)",
      "P(A|B)=P(A∩B)/P(A)",
      "P(A|B)=P(B)/P(A)",
    ],
    correctAnswer: "P(A|B)=P(B|A)P(A)/P(B)",
    explanation: "Bayes updates prior P(A) with likelihood P(B|A).",
    topicTags: ["probability"],
    difficulty: "Beginner",
  }),
]

const garchQuestions: QuizQuestion[] = [
  createMcq({
    id: "q2-01",
    text: "For GARCH(1,1) with omega=0.00001, alpha=0.05, beta=0.93, what is the unconditional variance?",
    options: ["0.0005", "0.0001", "0.0050", "0.00005"],
    correctAnswer: "0.0005",
    explanation: "omega/(1-alpha-beta)=0.00001/0.02=0.0005.",
    topicTags: ["time-series", "statistics"],
    difficulty: "Advanced",
  }),
  createMcq({
    id: "q2-02",
    text: "What does alpha + beta < 1 ensure in a GARCH(1,1) model?",
    options: ["Covariance stationarity", "No volatility clustering", "Negative variance", "Zero autocorrelation in returns"],
    correctAnswer: "Covariance stationarity",
    explanation: "It guarantees finite long-run variance.",
    topicTags: ["time-series"],
    difficulty: "Intermediate",
  }),
  createMcq({
    id: "q2-03",
    text: "In GARCH, a larger beta primarily means:",
    options: ["Slower decay of volatility shocks", "Higher unconditional mean return", "Lower persistence", "No leverage effect"],
    correctAnswer: "Slower decay of volatility shocks",
    explanation: "Beta controls persistence from past conditional variance.",
    topicTags: ["time-series"],
    difficulty: "Intermediate",
  }),
  createMcq({
    id: "q2-04",
    text: "Which model explicitly captures asymmetric (leverage) effects via log variance dynamics?",
    options: ["EGARCH", "ARCH", "MA(1)", "AR(1)"],
    correctAnswer: "EGARCH",
    explanation: "EGARCH models log variance and allows sign-dependent shock effects.",
    topicTags: ["time-series"],
    difficulty: "Intermediate",
  }),
  createMcq({
    id: "q2-05",
    text: "Given omega=0.00001, alpha=0.06, beta=0.90, epsilon_t^2=0.0009, sigma_t^2=0.0004, what is sigma_(t+1)^2?",
    options: ["0.000424", "0.000370", "0.000964", "0.000310"],
    correctAnswer: "0.000424",
    explanation: "omega + alpha*epsilon_t^2 + beta*sigma_t^2 = 0.000424.",
    topicTags: ["time-series"],
    difficulty: "Advanced",
  }),
  createMcq({
    id: "q2-06",
    text: "If alpha + beta = 1 in GARCH(1,1), the model is commonly called:",
    options: ["IGARCH", "ARCH-in-mean", "EWMA only", "ARIMA"],
    correctAnswer: "IGARCH",
    explanation: "Integrated GARCH implies very persistent variance with no finite long-run variance.",
    topicTags: ["time-series"],
    difficulty: "Advanced",
  }),
  createMcq({
    id: "q2-07",
    text: "Why do practitioners often use Student-t innovations instead of normal innovations in GARCH?",
    options: ["To model heavy tails", "To force zero variance", "To remove autocorrelation in levels", "To guarantee alpha+beta<1"],
    correctAnswer: "To model heavy tails",
    explanation: "Financial returns often have excess kurtosis.",
    topicTags: ["time-series", "statistics"],
    difficulty: "Intermediate",
  }),
  createMcq({
    id: "q2-08",
    text: "After fitting GARCH, standardized residual diagnostics should ideally show:",
    options: ["No serial correlation and no remaining ARCH", "Strong autocorrelation in squares", "Unit root in residuals", "Negative variance"],
    correctAnswer: "No serial correlation and no remaining ARCH",
    explanation: "A good volatility model leaves little predictable structure in residuals.",
    topicTags: ["time-series", "statistics"],
    difficulty: "Advanced",
  }),
  createMcq({
    id: "q2-09",
    text: "What key empirical feature of returns is GARCH built to model?",
    options: ["Volatility clustering", "Deterministic trend in price levels", "Constant variance", "Noisy bid-ask spread"],
    correctAnswer: "Volatility clustering",
    explanation: "Large shocks tend to be followed by large shocks.",
    topicTags: ["time-series"],
    difficulty: "Beginner",
  }),
  createMcq({
    id: "q2-10",
    text: "Multi-step conditional variance forecasts in stationary GARCH tend to:",
    options: ["Converge to the unconditional variance", "Explode to infinity always", "Converge to zero always", "Stay exactly constant at sigma_t^2"],
    correctAnswer: "Converge to the unconditional variance",
    explanation: "When alpha+beta<1, forecasts mean-revert in variance space.",
    topicTags: ["time-series"],
    difficulty: "Intermediate",
  }),
  createMcq({
    id: "q2-11",
    text: "In a GJR-GARCH style model, positive gamma generally implies:",
    options: ["Negative shocks increase volatility more than positive shocks", "Positive shocks increase volatility more", "No asymmetry", "Variance cannot be forecast"],
    correctAnswer: "Negative shocks increase volatility more than positive shocks",
    explanation: "Gamma loads on an indicator for negative shocks.",
    topicTags: ["time-series"],
    difficulty: "Advanced",
  }),
  createMcq({
    id: "q2-12",
    text: "Increasing omega (holding alpha and beta fixed) mainly affects:",
    options: ["Long-run variance level", "Sign of returns", "Sample size", "Lag order of ARMA mean"],
    correctAnswer: "Long-run variance level",
    explanation: "omega sets the variance intercept.",
    topicTags: ["time-series"],
    difficulty: "Intermediate",
  }),
  createMcq({
    id: "q2-13",
    text: "In GARCH(1,1), alpha primarily captures sensitivity to:",
    options: ["Recent shock magnitude (epsilon_t^2)", "Risk-free rate", "Long-run drift", "Order-book depth"],
    correctAnswer: "Recent shock magnitude (epsilon_t^2)",
    explanation: "Alpha weights new information shocks.",
    topicTags: ["time-series"],
    difficulty: "Intermediate",
  }),
  createMcq({
    id: "q2-14",
    text: "If alpha=0 and beta=0 in a GARCH(1,1), conditional variance equals:",
    options: ["A constant (omega)", "Random walk variance", "Zero", "Previous squared return"],
    correctAnswer: "A constant (omega)",
    explanation: "No dynamic terms remain in the variance recursion.",
    topicTags: ["time-series"],
    difficulty: "Beginner",
  }),
  createMcq({
    id: "q2-15",
    text: "Which parameter restrictions are standard in GARCH(1,1)?",
    options: ["omega>0, alpha>=0, beta>=0", "omega<0, alpha>1, beta<0", "alpha=beta=0.5 exactly", "omega unrestricted, alpha<0"],
    correctAnswer: "omega>0, alpha>=0, beta>=0",
    explanation: "These support non-negative conditional variance.",
    topicTags: ["time-series"],
    difficulty: "Intermediate",
  }),
  createMcq({
    id: "q2-16",
    text: "Approximate half-life of a volatility shock when alpha+beta=0.95 is:",
    options: ["About 13.5 periods", "About 2 periods", "About 1 period", "About 50 periods"],
    correctAnswer: "About 13.5 periods",
    explanation: "Half-life ≈ ln(0.5)/ln(0.95) ≈ 13.5.",
    topicTags: ["time-series", "statistics"],
    difficulty: "Advanced",
  }),
  createMcq({
    id: "q2-17",
    text: "GARCH models are usually estimated on:",
    options: ["Returns, not raw price levels", "Raw price levels only", "Order IDs", "Volume rank data only"],
    correctAnswer: "Returns, not raw price levels",
    explanation: "Variance stationarity assumptions are more appropriate for returns.",
    topicTags: ["time-series"],
    difficulty: "Beginner",
  }),
  createMcq({
    id: "q2-18",
    text: "A common test for remaining ARCH effects after model fitting is:",
    options: ["ARCH LM test", "ADF unit root test on prices", "Durbin-Watson on levels only", "Jarque-Bera on returns mean"],
    correctAnswer: "ARCH LM test",
    explanation: "It checks serial dependence in squared residuals.",
    topicTags: ["time-series", "statistics"],
    difficulty: "Intermediate",
  }),
  createMcq({
    id: "q2-19",
    text: "High alpha and low beta in GARCH usually indicates:",
    options: ["Strong short-run reaction, weaker persistence", "Weak reaction and very high persistence", "No conditional heteroskedasticity", "Negative conditional variance"],
    correctAnswer: "Strong short-run reaction, weaker persistence",
    explanation: "Alpha reacts to new shocks; beta carries persistence.",
    topicTags: ["time-series"],
    difficulty: "Advanced",
  }),
  createMcq({
    id: "q2-20",
    text: "If alpha+beta is close to 1, volatility forecasts are typically:",
    options: ["Highly persistent", "Unstable and negative", "Mean-reverting extremely fast", "Independent of past information"],
    correctAnswer: "Highly persistent",
    explanation: "Near-integrated variance dynamics imply slow decay of shocks.",
    topicTags: ["time-series"],
    difficulty: "Intermediate",
  }),
]

const executionQuestions: QuizQuestion[] = [
  createMcq({
    id: "q3-01",
    text: "When is a limit order usually preferred over a market order?",
    options: [
      "When spread is wide and urgency is low",
      "When immediate fill certainty is mandatory",
      "When you want to cross the spread quickly",
      "When market depth is deep and price certainty does not matter",
    ],
    correctAnswer: "When spread is wide and urgency is low",
    explanation: "Limit orders can reduce explicit spread costs when urgency is lower.",
    topicTags: ["execution", "microstructure"],
    difficulty: "Beginner",
  }),
  createMcq({
    id: "q3-02",
    text: "Implementation shortfall is best defined as:",
    options: [
      "Difference between decision-price paper return and realized execution return",
      "Difference between bid and ask",
      "Average daily volume minus traded volume",
      "Only temporary market impact",
    ],
    correctAnswer: "Difference between decision-price paper return and realized execution return",
    explanation: "It captures total execution costs, including timing and market impact.",
    topicTags: ["execution"],
    difficulty: "Intermediate",
  }),
  createMcq({
    id: "q3-03",
    text: "In Almgren-Chriss, optimal execution balances:",
    options: ["Market impact and timing risk", "Latency and memory usage", "Bid and ask count", "Profit and accounting tax"],
    correctAnswer: "Market impact and timing risk",
    explanation: "Trading too fast increases impact; too slow increases price risk.",
    topicTags: ["execution", "optimization"],
    difficulty: "Advanced",
  }),
  createMcq({
    id: "q3-04",
    text: "A VWAP strategy is most aligned with which objective?",
    options: ["Track volume-weighted benchmark", "Minimize code complexity", "Guarantee no slippage", "Always finish in first minute"],
    correctAnswer: "Track volume-weighted benchmark",
    explanation: "VWAP targets participation across expected market volume profile.",
    topicTags: ["execution"],
    difficulty: "Beginner",
  }),
  createMcq({
    id: "q3-05",
    text: "A TWAP schedule typically slices orders:",
    options: ["Evenly over time", "Based on quoted spread only", "Only at open and close", "Randomly with no schedule"],
    correctAnswer: "Evenly over time",
    explanation: "TWAP is time-uniform scheduling.",
    topicTags: ["execution"],
    difficulty: "Beginner",
  }),
  createMcq({
    id: "q3-06",
    text: "Adverse selection for passive orders means:",
    options: [
      "Counterparty may have superior information when they trade with you",
      "Your order is always rejected",
      "You always get midpoint fills",
      "Exchange fees go to zero",
    ],
    correctAnswer: "Counterparty may have superior information when they trade with you",
    explanation: "Being picked off by informed flow is a classic passive-order risk.",
    topicTags: ["microstructure", "execution"],
    difficulty: "Intermediate",
  }),
  createMcq({
    id: "q3-07",
    text: "An iceberg order primarily helps by:",
    options: ["Hiding full order size from displayed book", "Guaranteeing full fill", "Eliminating exchange fees", "Increasing spread"],
    correctAnswer: "Hiding full order size from displayed book",
    explanation: "Only a visible slice is shown, reducing signaling.",
    topicTags: ["execution", "microstructure"],
    difficulty: "Intermediate",
  }),
  createMcq({
    id: "q3-08",
    text: "If market volume in a 5-minute interval is 50,000 shares and your POV target is 10%, your child order target is:",
    options: ["5,000 shares", "500 shares", "10,000 shares", "50,000 shares"],
    correctAnswer: "5,000 shares",
    explanation: "POV target = 0.10 * interval volume.",
    topicTags: ["execution"],
    difficulty: "Intermediate",
  }),
  createMcq({
    id: "q3-09",
    text: "For a buy order, crossing from mid to ask incurs approximately:",
    options: ["Half-spread cost", "No spread cost", "Double-spread gain", "Only maker rebate"],
    correctAnswer: "Half-spread cost",
    explanation: "Relative to mid, buying at ask pays roughly half the spread.",
    topicTags: ["microstructure", "execution"],
    difficulty: "Intermediate",
  }),
  createMcq({
    id: "q3-10",
    text: "Temporary market impact generally increases when:",
    options: ["Order size is larger relative to available liquidity", "You trade fewer shares", "Spread tightens permanently", "Volatility is exactly zero"],
    correctAnswer: "Order size is larger relative to available liquidity",
    explanation: "Larger participation typically pushes execution price more.",
    topicTags: ["execution", "microstructure"],
    difficulty: "Beginner",
  }),
  createMcq({
    id: "q3-11",
    text: "A post-only order is designed to:",
    options: ["Add liquidity instead of taking liquidity", "Always execute immediately", "Cancel all child orders", "Force midpoint crossing"],
    correctAnswer: "Add liquidity instead of taking liquidity",
    explanation: "Post-only prevents immediate marketable execution.",
    topicTags: ["execution", "microstructure"],
    difficulty: "Intermediate",
  }),
  createMcq({
    id: "q3-12",
    text: "Why randomize child-order timing/sizes in execution algos?",
    options: ["Reduce signaling and predictability", "Guarantee better fill than VWAP", "Eliminate slippage entirely", "Disable exchange routing"],
    correctAnswer: "Reduce signaling and predictability",
    explanation: "Predictable flow can be exploited by other participants.",
    topicTags: ["execution"],
    difficulty: "Advanced",
  }),
  createMcq({
    id: "q3-13",
    text: "A common tradeoff when routing to dark pools is:",
    options: ["Lower footprint but uncertain fill probability", "Guaranteed fills with no delay", "Higher displayed queue priority", "Mandatory wider spreads"],
    correctAnswer: "Lower footprint but uncertain fill probability",
    explanation: "Dark venues can reduce impact but often have less certain execution.",
    topicTags: ["execution", "microstructure"],
    difficulty: "Intermediate",
  }),
  createMcq({
    id: "q3-14",
    text: "Queue position at best bid/ask matters mainly because it affects:",
    options: ["Fill probability and waiting time", "Accounting treatment", "Beta exposure", "Portfolio VaR formula"],
    correctAnswer: "Fill probability and waiting time",
    explanation: "Earlier queue priority typically fills sooner.",
    topicTags: ["microstructure"],
    difficulty: "Intermediate",
  }),
  createMcq({
    id: "q3-15",
    text: "Arrival price benchmark refers to:",
    options: ["Price at the decision time to trade", "Closing auction price", "Previous day's close", "Average fill of peers"],
    correctAnswer: "Price at the decision time to trade",
    explanation: "It anchors implementation shortfall calculations.",
    topicTags: ["execution"],
    difficulty: "Beginner",
  }),
  createMcq({
    id: "q3-16",
    text: "If a buy order reports +12 bps slippage vs benchmark, this usually means:",
    options: ["Execution was worse than benchmark", "Execution was better than benchmark", "No meaningful difference", "Benchmark was unavailable"],
    correctAnswer: "Execution was worse than benchmark",
    explanation: "For buys, positive slippage indicates paying more than benchmark.",
    topicTags: ["execution"],
    difficulty: "Intermediate",
  }),
  createMcq({
    id: "q3-17",
    text: "Which instruction emphasizes immediate execution but allows partial fill and cancellation of the rest?",
    options: ["IOC (Immediate-Or-Cancel)", "GTC", "Post-only", "AON"],
    correctAnswer: "IOC (Immediate-Or-Cancel)",
    explanation: "IOC executes what it can immediately, canceling remainder.",
    topicTags: ["execution"],
    difficulty: "Intermediate",
  }),
  createMcq({
    id: "q3-18",
    text: "A key reason to cap participation rate during volatile periods is to:",
    options: ["Avoid excessive footprint and impact", "Increase signaling", "Guarantee crossing spread", "Lock in adverse selection"],
    correctAnswer: "Avoid excessive footprint and impact",
    explanation: "High participation can move price materially against you.",
    topicTags: ["execution", "risk"],
    difficulty: "Advanced",
  }),
  createMcq({
    id: "q3-19",
    text: "Which scenario most likely favors market orders?",
    options: ["High urgency and small displayed spread", "Low urgency and wide spread", "Hidden liquidity discovery", "Queue building for maker rebates"],
    correctAnswer: "High urgency and small displayed spread",
    explanation: "When urgency dominates and spread cost is modest, taking liquidity is common.",
    topicTags: ["execution"],
    difficulty: "Beginner",
  }),
  createMcq({
    id: "q3-20",
    text: "Execution alpha decay risk refers to:",
    options: ["Signal value deteriorating while you wait to complete execution", "Exchange connectivity loss", "Variance forecast misspecification", "Incorrect tax lot mapping"],
    correctAnswer: "Signal value deteriorating while you wait to complete execution",
    explanation: "Delays can erode strategy edge before fills complete.",
    topicTags: ["execution", "time-series"],
    difficulty: "Advanced",
  }),
]

const riskMeasureQuestions: QuizQuestion[] = [
  createMcq({
    id: "q4-01",
    text: "What is the key limitation of VaR?",
    options: [
      "It does not describe loss severity beyond the threshold",
      "It always overestimates risk",
      "It cannot be computed from data",
      "It only applies to bonds",
    ],
    correctAnswer: "It does not describe loss severity beyond the threshold",
    explanation: "VaR is a quantile; tail magnitude past that quantile is not captured.",
    topicTags: ["risk"],
    difficulty: "Beginner",
  }),
  createMcq({
    id: "q4-02",
    text: "Expected Shortfall is coherent mainly because it satisfies:",
    options: ["Subadditivity", "Normality", "Stationarity", "Homoskedasticity"],
    correctAnswer: "Subadditivity",
    explanation: "Coherent measures must satisfy subadditivity among other axioms.",
    topicTags: ["risk", "statistics"],
    difficulty: "Intermediate",
  }),
  createMcq({
    id: "q4-03",
    text: "A 95% one-day VaR of $1M means:",
    options: [
      "About 5% chance daily loss exceeds $1M",
      "Maximum daily loss is $1M",
      "Expected daily loss is $1M",
      "95% chance of exactly $1M loss",
    ],
    correctAnswer: "About 5% chance daily loss exceeds $1M",
    explanation: "VaR is a percentile loss threshold, not a maximum.",
    topicTags: ["risk"],
    difficulty: "Beginner",
  }),
  createMcq({
    id: "q4-04",
    text: "Parametric (variance-covariance) VaR typically relies on:",
    options: ["Distributional assumptions for returns", "No assumptions at all", "Only order-book snapshots", "Full revaluation of every path"],
    correctAnswer: "Distributional assumptions for returns",
    explanation: "Usually normal or t assumptions are made.",
    topicTags: ["risk", "statistics"],
    difficulty: "Beginner",
  }),
  createMcq({
    id: "q4-05",
    text: "Historical simulation VaR is based on:",
    options: [
      "Empirical distribution of past returns/PnL",
      "Closed-form Black-Scholes greeks only",
      "Constant volatility assumption",
      "Bid-ask midpoint only",
    ],
    correctAnswer: "Empirical distribution of past returns/PnL",
    explanation: "It reuses realized history without parametric distribution fitting.",
    topicTags: ["risk", "statistics"],
    difficulty: "Intermediate",
  }),
  createMcq({
    id: "q4-06",
    text: "Stressed VaR differs from regular VaR by:",
    options: ["Using a historically stressed calibration window", "Using shorter holding period", "Ignoring correlations", "Assuming zero drift only"],
    correctAnswer: "Using a historically stressed calibration window",
    explanation: "It targets adverse market conditions.",
    topicTags: ["risk"],
    difficulty: "Intermediate",
  }),
  createMcq({
    id: "q4-07",
    text: "The square-root-of-time VaR scaling is most defensible when returns are:",
    options: ["IID with stable variance", "Strongly autocorrelated and heteroskedastic", "Pure jump with clustering", "Deterministic trend only"],
    correctAnswer: "IID with stable variance",
    explanation: "Scaling assumes independent increments and linear variance growth in time.",
    topicTags: ["risk", "statistics"],
    difficulty: "Advanced",
  }),
  createMcq({
    id: "q4-08",
    text: "Expected Shortfall at 97.5% is the:",
    options: [
      "Average loss in the worst 2.5% outcomes",
      "Median loss in all outcomes",
      "Maximum historical loss only",
      "Loss with exactly 97.5% probability",
    ],
    correctAnswer: "Average loss in the worst 2.5% outcomes",
    explanation: "ES averages the tail beyond the VaR quantile.",
    topicTags: ["risk", "statistics"],
    difficulty: "Beginner",
  }),
  createMcq({
    id: "q4-09",
    text: "Why can VaR violate diversification intuition in some cases?",
    options: ["It can fail subadditivity", "It always assumes independence", "It ignores position sizes", "It cannot handle options"],
    correctAnswer: "It can fail subadditivity",
    explanation: "Portfolio VaR may exceed sum of component VaRs in non-normal settings.",
    topicTags: ["risk"],
    difficulty: "Advanced",
  }),
  createMcq({
    id: "q4-10",
    text: "If daily return volatility is 2% and mean is near zero, normal 95% one-day VaR is closest to:",
    options: ["3.29%", "1.00%", "2.00%", "4.50%"],
    correctAnswer: "3.29%",
    explanation: "95% one-sided z ≈ 1.645, so VaR ≈ 1.645*2%=3.29%.",
    topicTags: ["risk", "statistics"],
    difficulty: "Intermediate",
  }),
  createMcq({
    id: "q4-11",
    text: "Marginal VaR measures:",
    options: ["Sensitivity of portfolio VaR to a small position change", "Absolute standalone VaR only", "Expected tail loss only", "Maximum drawdown"],
    correctAnswer: "Sensitivity of portfolio VaR to a small position change",
    explanation: "It is effectively a local derivative of VaR.",
    topicTags: ["risk"],
    difficulty: "Advanced",
  }),
  createMcq({
    id: "q4-12",
    text: "Incremental VaR is best interpreted as:",
    options: ["Change in portfolio VaR after adding/removing a position", "Difference between VaR and ES", "Annualized volatility", "Backtest p-value"],
    correctAnswer: "Change in portfolio VaR after adding/removing a position",
    explanation: "It quantifies contribution from a proposed trade or position.",
    topicTags: ["risk"],
    difficulty: "Intermediate",
  }),
  createMcq({
    id: "q4-13",
    text: "A common unconditional coverage backtest for VaR exceptions is:",
    options: ["Kupiec test", "ADF test", "Granger causality test", "Durbin-Watson test"],
    correctAnswer: "Kupiec test",
    explanation: "It compares observed exception frequency with expected frequency.",
    topicTags: ["risk", "statistics"],
    difficulty: "Intermediate",
  }),
  createMcq({
    id: "q4-14",
    text: "Stress testing complements VaR primarily by:",
    options: ["Evaluating extreme but plausible scenarios", "Replacing all statistical models", "Guaranteeing regulatory capital optimization", "Eliminating model risk"],
    correctAnswer: "Evaluating extreme but plausible scenarios",
    explanation: "Scenario analysis probes tail events not well represented in historical quantiles.",
    topicTags: ["risk"],
    difficulty: "Beginner",
  }),
  createMcq({
    id: "q4-15",
    text: "Which risk dimension is often underrepresented in basic VaR models?",
    options: ["Liquidity risk", "Currency notation", "Accounting calendar risk", "UI rendering risk"],
    correctAnswer: "Liquidity risk",
    explanation: "VaR often assumes frictionless liquidation.",
    topicTags: ["risk"],
    difficulty: "Intermediate",
  }),
  createMcq({
    id: "q4-16",
    text: "Which set contains the coherence axioms?",
    options: [
      "Monotonicity, translation invariance, positive homogeneity, subadditivity",
      "Unbiasedness, consistency, efficiency, normality",
      "Linearity, convexity, continuity, differentiability",
      "Skewness, kurtosis, mean, variance",
    ],
    correctAnswer: "Monotonicity, translation invariance, positive homogeneity, subadditivity",
    explanation: "These define coherent risk measures.",
    topicTags: ["risk", "statistics"],
    difficulty: "Advanced",
  }),
  createMcq({
    id: "q4-17",
    text: "Current Basel market-risk standards emphasize which tail metric over VaR?",
    options: ["Expected Shortfall", "Sharpe Ratio", "Tracking Error", "Sortino Ratio"],
    correctAnswer: "Expected Shortfall",
    explanation: "FRTB shifted from VaR to ES for better tail sensitivity.",
    topicTags: ["risk"],
    difficulty: "Intermediate",
  }),
  createMcq({
    id: "q4-18",
    text: "Correlation breakdown during crises mainly affects VaR by:",
    options: ["Making diversification benefits less reliable", "Eliminating all portfolio risk", "Fixing model misspecification automatically", "Reducing tail risk by default"],
    correctAnswer: "Making diversification benefits less reliable",
    explanation: "Stress correlations often rise, increasing joint losses.",
    topicTags: ["risk", "statistics"],
    difficulty: "Advanced",
  }),
  createMcq({
    id: "q4-19",
    text: "Maximum drawdown differs from VaR because drawdown is:",
    options: [
      "A path-dependent realized peak-to-trough loss metric",
      "A forward-looking quantile forecast",
      "Always smaller than VaR",
      "Only valid for fixed income",
    ],
    correctAnswer: "A path-dependent realized peak-to-trough loss metric",
    explanation: "Drawdown depends on path; VaR is a distribution quantile over horizon.",
    topicTags: ["risk"],
    difficulty: "Intermediate",
  }),
  createMcq({
    id: "q4-20",
    text: "If a model underestimates tail thickness, VaR exceptions are likely to be:",
    options: ["Too frequent", "Too rare", "Exactly as expected", "Always zero"],
    correctAnswer: "Too frequent",
    explanation: "Underestimated tails imply more realized breaches than predicted.",
    topicTags: ["risk", "statistics"],
    difficulty: "Advanced",
  }),
]

export const quizQuestionBank: Record<QuizId, QuizQuestion[]> = {
  "q-cond-prob": conditionalProbabilityQuestions,
  "q-garch": garchQuestions,
  "q-execution": executionQuestions,
  "q-risk-measures": riskMeasureQuestions,
}

export function getQuestionPoolForQuiz(quizId: string): QuizQuestion[] {
  return quizQuestionBank[quizId as QuizId] ?? []
}

export function getRandomQuestionsForQuiz(quizId: string, count = QUESTIONS_PER_ATTEMPT): QuizQuestion[] {
  const pool = getQuestionPoolForQuiz(quizId)
  if (pool.length <= count) {
    return [...pool]
  }
  return shuffle(pool).slice(0, count)
}

if (process.env.NODE_ENV !== "production") {
  for (const [quizId, questions] of Object.entries(quizQuestionBank)) {
    if (questions.length !== QUESTIONS_PER_POOL) {
      throw new Error(
        `Quiz ${quizId} must have exactly ${QUESTIONS_PER_POOL} questions, found ${questions.length}.`
      )
    }
  }
}
