import type { Difficulty, TopicId } from "./types"

export interface SkillMatrixQuizDefinition {
  skillId: string
  category: string
  skillName: string
  selfRating: number
  quizId: string
  quizTitle: string
  topicTags: TopicId[]
  difficulty: Difficulty
  timeLimitMinutes: number
}

export const MAX_SKILL_MATRIX_QUIZZES_IN_DB = 20

export const skillMatrixQuizDefinitions: SkillMatrixQuizDefinition[] = [
  {
    skillId: "sk-1",
    category: "Math & Probability",
    skillName: "Bayes' Theorem & Conditional Prob",
    selfRating: 4,
    quizId: "q-cond-prob",
    quizTitle: "Conditional Probability",
    topicTags: ["probability"],
    difficulty: "Intermediate",
    timeLimitMinutes: 15,
  },
  {
    skillId: "sk-2",
    category: "Math & Probability",
    skillName: "Stochastic Processes",
    selfRating: 3,
    quizId: "q-stochastic-processes",
    quizTitle: "Stochastic Processes",
    topicTags: ["probability", "time-series"],
    difficulty: "Advanced",
    timeLimitMinutes: 18,
  },
  {
    skillId: "sk-3",
    category: "Math & Probability",
    skillName: "Martingales & Filtrations",
    selfRating: 2,
    quizId: "q-martingales-filtrations",
    quizTitle: "Martingales & Filtrations",
    topicTags: ["probability"],
    difficulty: "Advanced",
    timeLimitMinutes: 18,
  },
  {
    skillId: "sk-4",
    category: "Statistics & Inference",
    skillName: "Hypothesis Testing & p-values",
    selfRating: 5,
    quizId: "q-hypothesis-testing",
    quizTitle: "Hypothesis Testing & p-values",
    topicTags: ["statistics"],
    difficulty: "Intermediate",
    timeLimitMinutes: 15,
  },
  {
    skillId: "sk-5",
    category: "Statistics & Inference",
    skillName: "Bayesian Inference",
    selfRating: 3,
    quizId: "q-bayesian-inference",
    quizTitle: "Bayesian Inference",
    topicTags: ["statistics", "probability"],
    difficulty: "Advanced",
    timeLimitMinutes: 18,
  },
  {
    skillId: "sk-6",
    category: "Time Series & ML",
    skillName: "ARIMA / GARCH Modeling",
    selfRating: 3,
    quizId: "q-arima-garch",
    quizTitle: "ARIMA / GARCH Modeling",
    topicTags: ["time-series", "statistics"],
    difficulty: "Advanced",
    timeLimitMinutes: 20,
  },
  {
    skillId: "sk-7",
    category: "Time Series & ML",
    skillName: "Regime Detection",
    selfRating: 2,
    quizId: "q-regime-detection",
    quizTitle: "Regime Detection",
    topicTags: ["time-series"],
    difficulty: "Advanced",
    timeLimitMinutes: 18,
  },
  {
    skillId: "sk-8",
    category: "Time Series & ML",
    skillName: "Volatility Forecasting",
    selfRating: 2,
    quizId: "q-garch",
    quizTitle: "GARCH Volatility Models",
    topicTags: ["time-series", "statistics"],
    difficulty: "Advanced",
    timeLimitMinutes: 20,
  },
  {
    skillId: "sk-9",
    category: "Optimization",
    skillName: "Mean-Variance Portfolio",
    selfRating: 3,
    quizId: "q-mean-variance",
    quizTitle: "Mean-Variance Portfolio",
    topicTags: ["optimization", "risk"],
    difficulty: "Intermediate",
    timeLimitMinutes: 16,
  },
  {
    skillId: "sk-10",
    category: "Optimization",
    skillName: "Convex Optimization (KKT)",
    selfRating: 2,
    quizId: "q-convex-kkt",
    quizTitle: "Convex Optimization (KKT)",
    topicTags: ["optimization"],
    difficulty: "Advanced",
    timeLimitMinutes: 18,
  },
  {
    skillId: "sk-11",
    category: "Microstructure & Execution",
    skillName: "Limit Order Books",
    selfRating: 4,
    quizId: "q-limit-order-books",
    quizTitle: "Limit Order Books",
    topicTags: ["microstructure", "execution"],
    difficulty: "Intermediate",
    timeLimitMinutes: 15,
  },
  {
    skillId: "sk-12",
    category: "Microstructure & Execution",
    skillName: "Market Impact Models",
    selfRating: 2,
    quizId: "q-market-impact-models",
    quizTitle: "Market Impact Models",
    topicTags: ["microstructure", "execution"],
    difficulty: "Advanced",
    timeLimitMinutes: 18,
  },
  {
    skillId: "sk-13",
    category: "Microstructure & Execution",
    skillName: "Order Execution & Slippage",
    selfRating: 3,
    quizId: "q-execution",
    quizTitle: "Order Execution & Slippage",
    topicTags: ["execution", "microstructure"],
    difficulty: "Intermediate",
    timeLimitMinutes: 12,
  },
  {
    skillId: "sk-14",
    category: "Risk Management",
    skillName: "VaR & Expected Shortfall",
    selfRating: 4,
    quizId: "q-risk-measures",
    quizTitle: "Risk Measures & VaR",
    topicTags: ["risk", "statistics"],
    difficulty: "Intermediate",
    timeLimitMinutes: 15,
  },
  {
    skillId: "sk-15",
    category: "Risk Management",
    skillName: "Stop-loss Discipline",
    selfRating: 3,
    quizId: "q-stop-loss-discipline",
    quizTitle: "Stop-loss Discipline",
    topicTags: ["risk", "execution"],
    difficulty: "Intermediate",
    timeLimitMinutes: 14,
  },
  {
    skillId: "sk-16",
    category: "Python Engineering",
    skillName: "NumPy / Pandas Pipelines",
    selfRating: 5,
    quizId: "q-numpy-pandas",
    quizTitle: "NumPy / Pandas Pipelines",
    topicTags: ["python"],
    difficulty: "Intermediate",
    timeLimitMinutes: 14,
  },
  {
    skillId: "sk-17",
    category: "Python Engineering",
    skillName: "Backtesting Frameworks",
    selfRating: 4,
    quizId: "q-backtesting-frameworks",
    quizTitle: "Backtesting Frameworks",
    topicTags: ["python", "risk"],
    difficulty: "Advanced",
    timeLimitMinutes: 18,
  },
  {
    skillId: "sk-18",
    category: "C++ / Systems",
    skillName: "Memory Management",
    selfRating: 2,
    quizId: "q-memory-management",
    quizTitle: "C++ Memory Management",
    topicTags: ["cpp", "debugging"],
    difficulty: "Intermediate",
    timeLimitMinutes: 15,
  },
  {
    skillId: "sk-19",
    category: "C++ / Systems",
    skillName: "Low-latency Patterns",
    selfRating: 1,
    quizId: "q-low-latency-patterns",
    quizTitle: "Low-latency Patterns",
    topicTags: ["cpp", "debugging"],
    difficulty: "Advanced",
    timeLimitMinutes: 18,
  },
]

export const skillMatrixQuizDefinitionsForDb = skillMatrixQuizDefinitions.slice(0, MAX_SKILL_MATRIX_QUIZZES_IN_DB)
